package com.react.chat.domain.enumFiles;

public enum Interests {
    ISTJ,ISTP,ISFJ,ISFP,INTJ,INTP,INFJ,INFP,ESTJ,ESFJ,ESFP,ESTP,ENTJ,ENTP,ENFJ,ENFP,
    EXERCISE,FITNESS,RUNNING,HEALTH,VEGETARIAN,
    DESSERT,CAFE,COFFEE,BREAD,SALAD,RESTAURANT,SUSHI,FASTFOOD,ALCOHOL,BEER,WINE,WHISKY,
    MOVIE,DRAMA,READING,ANIME,MUSIC,SHOPING,PICTURE,
    FINANCIAL,STOCK,
    CULTURE,BANKING,INDUSTRY,HEALTHMEDICINE,IT,DESIGN,PE,
    CONVERSATION,DATE,FRIEND,MARRY,MANIA,DIET,ART,FASHION,BEAUTY,
    STUDY,JOB,EMPLOYMENT,PARTTIMEJOB,INTERN
}
