package com.react.chat.domain.enumFiles;

public enum Interests {
    // *****    관심사    *****
    // MBTI
    ISTJ,ISTP,ISFJ,ISFP,INTJ,INTP,INFJ,INFP,ESTJ,ESFJ,ESFP,ESTP,ENTJ,ENTP,ENFJ,ENFP,
    // 운동
    EXERCISE,FITNESS,RUNNING,HEALTH,VEGETARIAN,
    // 음식
    DESSERT,CAFE,COFFEE,BREAD,SALAD,RESTAURANT,SUSHI,FASTFOOD,ALCOHOL,BEER,WINE,WHISKY,
    // 취미
    MOVIE,DRAMA,READING,ANIME,MUSIC,SHOPING,PICTURE,
    // 재테크
    FINANCIAL,STOCK,
    // 전공
    CULTURE,BANKING,INDUSTRY,HEALTHMEDICINE,IT,DESIGN,PE,
    //라이프
    CONVERSATION,DATE,FRIEND,MARRY,MANIA,DIET,ART,FASHION,BEAUTY,
    //커리어
    STUDY,JOB,EMPLOYMENT,PARTTIMEJOB,INTERN
}
